
#Server configuration settings
[server]
	#The time in ticks the server will wait when a dimension was queued to unload. This can be useful when rapidly loading and unloading dimensions, like e.g. throwing items through a nether portal a few time per second.
	#Range: > 0
	dimensionUnloadQueueDelay = 20

