
["World Generation"]
	#Set to FALSE to prevent 'Thermal Series' Copper from generating.
	Copper = false
	#Set to FALSE to prevent 'Thermal Series' Lead from generating.
	Lead = false
	#Set to FALSE to prevent 'Thermal Series' Silver from generating.
	Silver = false
	#Set to FALSE to prevent 'Thermal Series' Nickel from generating.
	Nickel = false

